apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  labels:
    app: qa-api
    release: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  POSTGRES_HOST: {{ .Values.database.host | quote }}
  SQLALCHEMY_DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" 
    .Values.database.user 
    .Values.database.password 
    .Values.database.host 
    (.Values.postgres.port | int)
    .Values.database.name | quote }}