apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qa-api
  template:
    metadata:
      labels:
        app: qa-api
    spec:
      containers:
        - name: api
          image: qa-api:v1.2.3
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-env
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
